In [2]:
import numpy as np

In [5]:
test_array = np.array([2,4,6,8],float)
print(test_array)
type(test_array[3])

[2. 4. 6. 8.]


numpy.float64

In [10]:
test_array = np.array([2,4,6,"3"],float)
test_array
type(test_array[3])

numpy.float64

In [17]:
a = np.array([[1,2,3],[4,5,6]],int)
print(a[0,0])
print(a[0][0])

1
1


In [19]:
a[0,0] = 7
print(a)

[[7 2 3]
 [4 5 6]]


In [27]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]],int)
print(a[1,3])

9


In [32]:
np.arange(30).reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [36]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [46]:
np.eye(5,8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.]])

In [47]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [50]:
test_matrix = np.array([[1,2,3],[4,5,6]],float)
scalar = 5
print(test_matrix*scalar)

[[ 5. 10. 15.]
 [20. 25. 30.]]


In [56]:
print(test_matrix/scalar)

[[0.2 0.4 0.6]
 [0.8 1.  1.2]]


In [58]:
test_a = np.array([1,3,0],float)
test_b = np.array([5,2,1],float)
print(test_a == test_b)

[False False False]
